### PR TITLE
add stack and column number if available + make request asynch and remove deprecated ActiveX

### PR DESCRIPTION
**Pull request by johanneswilm**

### CODE REVIEW

**Comment by johanneswilm** [comment]
Hey @jojax, i think it's time to make some minor adjustments to this plugin given the changes browser have had in recent years. It would be good if you could merge this. If you still know of any browser relying on ActiveX, we should probably add that back.

**Comment by johanneswilm** [comment]
Hey @Natim . Could we make a new release out of this?

**Comment by Natim** [comment]
Here you go: https://github.com/jojax/django-js-error-hook/releases/tag/0.5

**Comment by johanneswilm** [comment]
thank you!

**Pull request merged**
